### ISSUE TITLE
Does not compile on nodejs v0.10.11

### ISSUE THREAD

**Issue by mheiniger** [pkrumins/node-png#32]
I tried to install node-png with nodejs v0.10.11 on a fresh install of Ubuntu 13.04:

$ npm install png
npm http GET https://registry.npmjs.org/png
npm http 304 https://registry.npmjs.org/png

> png@3.0.2 install /home/michael/node-png/node_modules/png
> node-gyp rebuild

make: Entering directory `/home/michael/node-png/node_modules/png/build'
  CXX(target) Release/obj.target/png/src/common.o
  CXX(target) Release/obj.target/png/src/png_encoder.o
In file included from ../src/png_encoder.cpp:3:0:
../src/png_encoder.h:4:17: fatal error: png.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/png/src/png_encoder.o] Error 1
make: Leaving directory`/home/michael/node-png/node_modules/png/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.8.0-25-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/michael/node-png/node_modules/png
gyp ERR! node -v v0.10.11
gyp ERR! node-gyp -v v0.10.0
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by mheiniger** [comment]
Ok, i don't know C++, but after learning the difference between `#include <png.h>` and `#include "png.h"` i found out that not the local file was meant. And i also found out, that installing libpng is not enough, i needed to install `libpng-dev`.
Maybe you could mention that in the docs or add it to the dependencies.

Its working for me now. Thanks for your module :+1:
